---

- name: Make sure easy-install.pth is on its place
  shell: cp /opt/zato/current/lib/python2.7/site-packages/easy-install.pth \
    /opt/zato/current/eggs/
  become_user: zato
  when: ansible_os_family == "Debian"

- name: Make sure easy-install.pth is on its place
  shell: cp /opt/zato/current/code/lib/python2.7/site-packages/easy-install.pth \
    /opt/zato/current/code/eggs/
  become_user: zato
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Downgrade six to 1.6.1
  pip:
    name: six
    version: 1.6.1
  become_user: root
  when: ansible_distribution == "Debian"

- name: Install zato-apitests on Debian-based systems
  pip:
    name: zato-apitest
  become_user: root
  when: ansible_os_family == "Debian"

- name: Upgrade setuptools on CentOS 7
  shell: easy_install setuptools==1.1.6
  become_user: root
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Install zato-apitests on RedHat-based systems
  pip:
    name: zato-apitest
  become_user: root
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
