---

# These tasks won't work on localhost without become: no/False
- name: Generate variables from a template
  template:
    src={{ playbook_dir }}/roles/add_package_to_repo/templates/main.j2
    dest={{ playbook_dir }}/roles/{{ item }}
  with_items:
    - add_package_to_repo/defaults/main.yml
    - sign_package/defaults/main.yml
  delegate_to: localhost
  become: False

- name: Generate repository definition for Centos
  template:
    src={{ playbook_dir }}/roles/prepare_install_zato/templates/zato-2.0.repo.j2
    dest={{ playbook_dir }}/roles/prepare_install_zato/files/zato-2.0.repo
  delegate_to: localhost
  become: False
  when: '"redhat" in system'
