---

# Some packages installed here are required by zato-apitest package

- name: Install additional packages on Debian-based systems
  apt: name={{ item }} state=present update_cache=yes
  when: ansible_os_family == "Debian"
  with_items:
    - acl
    - htop
    - ranger
    - vim
    - libpq-dev
    - python-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev

- name: Install epel-release
  yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"

- name: Install additional packages on RedHat-based systems
  yum: name={{ item }} state=present enablerepo=epel
  when: ansible_os_family == "RedHat"
  with_items:
    - acl
    - vim
    - libselinux-python
    - libpqxx-devel
    - libxml2-devel
    - libxslt-devel
    - python-devel
    - libyaml-devel
