---

- name: Copy repo box's ca certificate
  copy: src={{ repo['host'] }}.crt
    dest=/usr/local/share/ca-certificates
  become_user: root

- name: Update ca certificates
  shell: update-ca-certificates
  become_user: root

- name: Update cache
  apt: update_cache=yes

# Notice that apt-key has to be performed by root
- name: Add the package signing key
  shell: curl -s https://{{ repo['host'] }}/repo/zato-deb-test.pgp.asc | \
    apt-key add -
  become_user: root

- name: Add Zato test repository on Debian-based systems
  shell: apt-add-repository \
    https://{{ repo['host'] }}/repo/stable/2.0/{{ distro }}
  become_user: root
  when: release == "stable"

- name: Add Zato custom test repository on Debian-based systems
  shell: apt-add-repository \
    https://{{ repo['host'] }}/repo/{{ release }}/{{ distro }}
  become_user: root
  when: release != "stable"
