---

- name: Send a signed deb package to official Zato repository
  shell: rsync -az --delete -e ssh "{{ source_dir }}" \
    vagrant@192.168.103.103:/home/vagrant/deb
  become_user: vagrant

#- name: Send a signed deb package to official Zato repository
#  synchronize:
#    src: "{{ source_dir }}"
#    dest: rsync://192.168.103.103/home/vagrant/deb/
#  become_user: vagrant
#  when: ansible_os_family == "Debian"
#  register: package_debian_sent
#
#- name: Send a signed rpm package to official Zato repository
#  synchronize:
#    src: "{{ source_dir }}"
#    dest: rsync://192.168.103.103/home/vagrant/rpm/
#  become_user: root
#  when: ansible_os_family == "RedHat"
#  register: package_centos_sent
