---

# Create a custom repo directory. Non-custom directories are created
# by Vagrant provision when rpm repo box is created.
- name: Create a root repo directory for a custom (not 'stable') Zato package
  file:
    name: /var/www/repo/{{ repository }}
    state: directory
  when: release != 'stable'

- name: Add a new package to a repository at repo-box-centos
  copy:
    src: ./output/{{ system }}/{{ zato_package }}
    dest: /var/www/repo/{{ repository }}

- name: Sign the package using 'Expect' program
  shell: /vagrant/files/sign_rpm_with_expect.exp {{ release }} {{ distro }} \
    {{ codename }} {{ arch }} {{ version }} {{ repo_version }}
  args:
    chdir: /var/www/repo/{{ repository }}

- name: Update the repo (effectively add the package)
  shell: createrepo --cache ./cache --update ./
  args:
    chdir: /var/www/repo/{{ repository }}
