---

  - name: Install required packages
    apt: name={{ item }} state=present
    with_items:
      - build-essential
      - tcl8.5

# Download 3.0.7, because compiling the latest stable (3.2.7) is failing
# with current Ansible infrastructure
  - name: Download Redis
    get_url: url=http://download.redis.io/releases/redis-3.0.7.tar.gz dest=./

  - name: Unpack Redis
    unarchive: src=./redis-3.0.7.tar.gz dest=./ copy=no

  - name: Compile Redis
    shell: make chdir=./redis-3.0.7

  - name: Install Redis
    shell: make install chdir=./redis-3.0.7

  - name: Configure Redis to run in the background
    shell: echo -n | ./install_server.sh chdir=./redis-3.0.7/utils

  - name: Run Redis
    service: name=redis_6379 state=started
