---

- name: Clone zato-build repository on Debian-based systems
  git: repo=https://github.com/zatosource/zato-build.git
       dest=/opt/tmp/
       clone=yes
  when: ansible_os_family == "Debian"

- name: Clone zato-build repository on Debian-based systems
  git: repo=https://github.com/zatosource/zato-build.git
       dest=/opt/tmp2/
       clone=yes
  when: ansible_distribution == "CentOS"

- name: Run build-zato.sh script on Debian-based systems
  shell: /opt/tmp/deb/build-zato.sh {{ branch }} \
                                    {{ version }} \
                                    {{ release }}
  when: ansible_os_family == "Debian"

- name: Run build-zato.sh script on CentOS
  shell: >
    /opt/tmp2/rhel{{ ansible_distribution_major_version }}/build-zato.sh 
    {{ branch }} 
    {{ version }} 
    {{ release }} 
  when: ansible_distribution == "CentOS"

- name: Copy Zato package on Debian-based i386 systems
  fetch: >
    src=/opt/tmp/deb/zato-{{ version }}-{{ release }}_i386-{{ ansible_distribution_release }}.deb 
    dest=./output/{{ system }}/
    flat=yes
  when: ansible_os_family == "Debian" and ansible_userspace_architecture == "i386"

- name: Copy Zato package on Debian-based amd64 systems
  fetch: >
    src=/opt/tmp/deb/zato-{{ version }}-{{ release }}_amd64-{{ ansible_distribution_release }}.deb 
    dest=./output/{{ system }}/
    flat=yes
  when: ansible_os_family == "Debian" and ansible_userspace_architecture == "x86_64"

- name: Copy Zato package on CentOS
  fetch: >
    src=/root/rpmbuild/RPMS/{{ ansible_userspace_architecture }}/zato-{{ version }}-{{ release }}.el{{ ansible_distribution_major_version }}.{{ ansible_userspace_architecture }}.rpm
    dest=./output/{{ system }}/
    flat=yes
  when: ansible_distribution == "CentOS"
