---

- hosts: localhost
  vars_files:
    - vars/main.yml

  tasks:

    - name: Make sure a repo box is running
      shell: vagrant up chdir=./vm/{{ repo['host'] }}

    - name: Copy vagrant user's private key
      shell: cp  ./.vagrant/machines/default/virtualbox/private_key \
        ../../files/vagrant_key/{{ repo['host'] }}_private_key
        chdir=./vm/{{ repo['host'] }}

- hosts: "{{ repo['host'] }}"
  become: True
  remote_user: vagrant
  vars:
    ansible_ssh_private_key_file:
      ./files/vagrant_key/{{ repo['host'] }}_private_key
  vars_files:
    - vars/main.yml

  pre_tasks:

    - name: Install acl package
      apt: name=acl state=present
      when: ansible_os_family == "Debian"

    - name: Fetch deb repo box's certificate
      fetch: dest=./roles/prepare_install_zato/files/ \
        src=/etc/apache2/ssl/{{ repo['host'] }}.crt
        flat=yes
        fail_on_missing=yes
      when: ansible_os_family == "Debian"

    - name: Fetch rpm repo box's certificate
      fetch: dest=./roles/prepare_install_zato/files/ \
        src=/etc/httpd/ssl/{{ repo['host'] }}.crt
        flat=yes
        fail_on_missing=yes
      when: ansible_os_family == "RedHat"

  roles:

    - add_package_to_repo
