---

- name: Prepare a Vagrant box
  hosts: localhost
- include: prepare_box.yml

- name: Build a Zato package
  hosts: "{{ host }}"
  become: True
  vars_files:
    - environments/testing/host_vars/{{ host }}.yml
  roles:
    - build_package

- name: Clean up the build environment
  hosts: localhost
- include: clean.yml

- name: Add a new Zato package to a test repository
  hosts: localhost
- include: add_package_to_repo.yml

- name: Prepare a test environment
  hosts: localhost
- include: prepare_box.yml

- name: Test a Zato quickstart environment
  hosts: "{{ host }}"
- include: quickstart_redis_sqlite.yml

- name: Clean up
  hosts: localhost
- include: clean.yml
