---

- name: Prepare a Vagrant box
  hosts: localhost
- include: prepare_box.yml

- name: Build a Zato package
  hosts: "{{ host }}"
  become: True
  roles:
    - build_package

- name: Fetch a Zato package
  hosts: "{{ host }}"
  become: True
  roles:
    - { role: fetch_package,
        when: ( package_build_deb.changed and package_build_deb.rc == 0 )
           or ( package_build_rpm.changed and package_build_rpm.rc == 0 ) }

- name: Clean up the build environment
  hosts: localhost
- include: clean.yml
  when: hostvars[host].package_fetched_debian_i386.changed or
    hostvars[host].package_fetched_debian_amd64.changed or
    hostvars[host].package_fetched_centos.changed

- name: Add a new Zato package to a test repository
  hosts: localhost
- include: add_package_to_repo.yml
  when: hostvars[host].package_fetched_debian_i386.changed or
    hostvars[host].package_fetched_debian_amd64.changed or
    hostvars[host].package_fetched_centos.changed

- name: Prepare a test environment
  hosts: localhost
- include: prepare_box.yml
  when: hostvars[host].package_fetched_debian_i386.changed or
    hostvars[host].package_fetched_debian_amd64.changed or
    hostvars[host].package_fetched_centos.changed

- name: Test a Zato quickstart environment
  hosts: "{{ host }}"
- include: quickstart_redis_sqlite.yml
  when: hostvars[host].package_fetched_debian_i386.changed or
    hostvars[host].package_fetched_debian_amd64.changed or
    hostvars[host].package_fetched_centos.changed

- name: Sign Zato package
  hosts: localhost
- include: sign_package.yml
  when:
    - ansible_distribution_major_version != "8"
    - ( hostvars[host].nosetest_debian_positive and
      hostvars[host].apitest_debian_positive ) or
      ( hostvars[host].nosetest_centos_positive and
      hostvars[host].apitest_centos_positive )

- name: Sign Zato package on Debian 8
  hosts: localhost
- include: sign_package.yml
  when:
    - ansible_distribution_major_version == "8"
    - hostvars[host].nosetest_debian_positive
