---

- hosts: localhost
  ignore_errors: yes

  tasks:

    - name: Destroy vagrant box
      shell: vagrant destroy --force chdir=./vm/{{ system }}

    - name: Remove directories and files
      file: path=./vm/{{ system }}/{{ item }} state=absent
      with_items:
        - .vagrant
        - synced
        - Vagrantfile

    - name: Remove vagrant user's private_key
      file: path=./files/vagrant_key/private_key state=absent
