---

- hosts: localhost

  tasks:

    - name: Prepare variable file
      template: src=./templates/main.j2 dest=./vars/main.yml
      delegate_to: localhost
      become: False

- hosts: localhost
  vars:
    repo_datetime: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - ./vars/main.yml

  tasks:

    # These tasks won't work on localhost without become: no/False
    - name: Generate variables for a template
      template:
        src={{ playbook_dir }}/roles/add_package_to_repo/templates/main.j2
        dest={{ playbook_dir }}/roles/add_package_to_repo/defaults/main.yml
      delegate_to: localhost
      become: False

    - name: Generate repository definition for Centos
      template:
        src={{ playbook_dir }}/roles/prepare_install_zato/templates/zato-2.0.repo.j2
        dest={{ playbook_dir }}/roles/prepare_install_zato/files/zato-2.0.repo
      delegate_to: localhost
      become: False
