---

- hosts: sign-deb, sign-rpm
  remote_user: vagrant

  tasks:

    - name: Create a directory to store a updated repo
      file:
        path: /vagrant/repo-{{ timestamp }}
        state: directory
        mode: 0755

    - name: Copy deb repository files to 'vagrant' directory
      shell: cp -r /opt/aptly/.aptly/public/repo /vagrant/repo-{{ timestamp }}
      when: ansible_hostname == "sign-deb"

    - name: Copy rpm repository files to 'vagrant' directory
      shell: cp -r /var/www/repo /vagrant/repo-{{ timestamp }}
      when: ansible_hostname == "sign-rpm"
