---

- hosts: "{{ host }}"
  become: True

  roles:

    - install_zato_dependencies
    - install_redis
    - install_mysql
    - configure_mysql
    - prepare_install_zato
    - install_zato
    - create_quickstart_mysql
    - test_quickstart
