---

- hosts: "{{ host }}"
  become: True
  vars:
    require_apitests: true
    require_nosetests: true

  roles:

    - install_zato_dependencies
    - install_redis
    - prepare_install_zato
    - install_zato
    - install_zato_apitest
    - create_quickstart
    - test_quickstart
