---

- hosts: "{{ host }}"
  become: True

  roles:

    - install_zato_dependencies
    - install_redis
    - prepare_install_zato
    - install_zato
    - install_zato_apitest
    - create_quickstart
    - test_quickstart
