---

- hosts: localhost
  vars_files:
    - environments/testing/host_vars/{{ host }}.yml

  tasks:

    - name: Make sure the signbox is running
      shell: vagrant up chdir=./vm/{{ sign_host }}/

    - name: Copy vagrant user's private key
      shell: cp  ./.vagrant/machines/default/virtualbox/private_key \
        ../../files/vagrant_key/{{ sign_host }}_private_key
        chdir=./vm/{{ sign_host }}/

- hosts: "{{ sign_host }}"
  become: True
  remote_user: vagrant
  vars_files:
    - environments/testing/host_vars/{{ host }}.yml
  vars:
    ansible_ssh_private_key_file:
      ./files/vagrant_key/{{ sign_host }}_private_key

  pre_tasks:

    - name: Install acl package
      apt: name=acl state=present
      when: ansible_os_family == "Debian"

  roles:

    - sign_package
